<%@ Control Language="C#" AutoEventWireup="true" CodeFile="EbebabaAdminMenuControl.ascx.cs" Debug="true" Inherits="EbebabaAdminMenuControl" %>
<style type="text/css">

  .baslik
{   background-image:url('images/menu_bg.gif');  font-name:"Tahoma";  font-size:11px ; background-repeat :repeat-x; height: 18px ; width : 100%  ;  
    
    
    }

</style>
<asp:TreeView ID="Menu" runat="server" AutoGenerateDataBindings="False" CollapseImageUrl="~/administrator_ebebaba_pages/images/menu_bg_sol.gif"
    ExpandImageUrl="~/administrator_ebebaba_pages/images/menu_bg_sag.gif" Font-Names="Tahoma" Font-Size="11px" ForeColor="Black"
    NodeIndent="0" NodeWrap="True" NoExpandImageUrl="~/administrator_ebebaba_pages/images/menu_bg2.gif" Width="100%" ExpandDepth="0">
    <ParentNodeStyle CssClass="baslik" Width="100%" />
    <LevelStyles>
        <asp:TreeNodeStyle CssClass="baslik" Font-Underline="False" />
    </LevelStyles>
    <SelectedNodeStyle BackColor="#FFFFC0" />
</asp:TreeView>
