<%@ Control Language="C#" AutoEventWireup="true" CodeFile="infertilite.ascx.cs" Inherits="infertilite" %>
<style type="text/css">

  .baslik
{    background-image:url('images/menu_bg3.gif'); font-size:11px ; background-repeat :repeat-x; height: 22px ; width : 100%  ;  
    
   
    }

</style>
<asp:TreeView ID="Menu" runat="server" AutoGenerateDataBindings="False" CollapseImageUrl="~/uyeModulu/images/siklus_spl.gif"
    ExpandImageUrl="~/uyeModulu/images/siklus_sag.gif" Font-Names="Arial" Font-Size="11px" ForeColor="Black"
    NodeIndent="0" NodeWrap="True" Width="100%" Font-Underline="False" MaxDataBindDepth="1">
    <ParentNodeStyle Width="100%" Font-Bold="False" BackColor="#F3F3F3" />
    <LevelStyles>
        <asp:TreeNodeStyle CssClass="baslik" Font-Underline="False" />
    </LevelStyles>
    <SelectedNodeStyle Font-Underline="True" ForeColor="#DD5555" HorizontalPadding="0px" VerticalPadding="0px" />
    <HoverNodeStyle BackColor="Transparent" Font-Underline="False" Width="100%" />
    <NodeStyle Font-Names="Arial" Font-Size="11px" ForeColor="Black" HorizontalPadding="0px"
        NodeSpacing="0px" VerticalPadding="0px" />
    <LeafNodeStyle Font-Bold="True" Font-Names="Arial" Font-Size="11px" />
</asp:TreeView>
            <asp:Label ID="Label1" runat="server" Font-Names="Arial" Font-Size="11px" ForeColor="Red" Font-Bold="False"></asp:Label>
